/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blackguard_Scene_LOCALE */

#ifndef _Included_blackguard_Scene_LOCALE
#define _Included_blackguard_Scene_LOCALE
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
