/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_BlackguardView_SoftKeyboardKey */

#ifndef _Included_com_dialectek_blackguard_BlackguardView_SoftKeyboardKey
#define _Included_com_dialectek_blackguard_BlackguardView_SoftKeyboardKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dialectek_blackguard_BlackguardView_SoftKeyboardKey_PLAIN_KEY
#define com_dialectek_blackguard_BlackguardView_SoftKeyboardKey_PLAIN_KEY 0L
#undef com_dialectek_blackguard_BlackguardView_SoftKeyboardKey_HIDE_KEY
#define com_dialectek_blackguard_BlackguardView_SoftKeyboardKey_HIDE_KEY 1L
#undef com_dialectek_blackguard_BlackguardView_SoftKeyboardKey_CAPS_LOCK_KEY
#define com_dialectek_blackguard_BlackguardView_SoftKeyboardKey_CAPS_LOCK_KEY 2L
#ifdef __cplusplus
}
#endif
#endif
