/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_BlackguardView_SoftKeyboardRow */

#ifndef _Included_com_dialectek_blackguard_BlackguardView_SoftKeyboardRow
#define _Included_com_dialectek_blackguard_BlackguardView_SoftKeyboardRow
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
