/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_SoundManager */

#ifndef _Included_com_dialectek_blackguard_SoundManager
#define _Included_com_dialectek_blackguard_SoundManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dialectek_blackguard_SoundManager_openDungeonSound
#define com_dialectek_blackguard_SoundManager_openDungeonSound 0L
#undef com_dialectek_blackguard_SoundManager_pickupGoldSound
#define com_dialectek_blackguard_SoundManager_pickupGoldSound 1L
#undef com_dialectek_blackguard_SoundManager_pickupObjectSound
#define com_dialectek_blackguard_SoundManager_pickupObjectSound 2L
#undef com_dialectek_blackguard_SoundManager_hitMonsterSound
#define com_dialectek_blackguard_SoundManager_hitMonsterSound 3L
#undef com_dialectek_blackguard_SoundManager_hitPlayerSound
#define com_dialectek_blackguard_SoundManager_hitPlayerSound 4L
#undef com_dialectek_blackguard_SoundManager_missMonsterSound
#define com_dialectek_blackguard_SoundManager_missMonsterSound 5L
#undef com_dialectek_blackguard_SoundManager_missPlayerSound
#define com_dialectek_blackguard_SoundManager_missPlayerSound 6L
#undef com_dialectek_blackguard_SoundManager_killMonsterSound
#define com_dialectek_blackguard_SoundManager_killMonsterSound 7L
#undef com_dialectek_blackguard_SoundManager_levelUpSound
#define com_dialectek_blackguard_SoundManager_levelUpSound 8L
#undef com_dialectek_blackguard_SoundManager_throwObjectSound
#define com_dialectek_blackguard_SoundManager_throwObjectSound 9L
#undef com_dialectek_blackguard_SoundManager_zapWandSound
#define com_dialectek_blackguard_SoundManager_zapWandSound 10L
#undef com_dialectek_blackguard_SoundManager_dipObjectSound
#define com_dialectek_blackguard_SoundManager_dipObjectSound 11L
#undef com_dialectek_blackguard_SoundManager_eatFoodSound
#define com_dialectek_blackguard_SoundManager_eatFoodSound 12L
#undef com_dialectek_blackguard_SoundManager_quaffPotionSound
#define com_dialectek_blackguard_SoundManager_quaffPotionSound 13L
#undef com_dialectek_blackguard_SoundManager_readScrollSound
#define com_dialectek_blackguard_SoundManager_readScrollSound 14L
#undef com_dialectek_blackguard_SoundManager_stairsSound
#define com_dialectek_blackguard_SoundManager_stairsSound 15L
#undef com_dialectek_blackguard_SoundManager_dieSound
#define com_dialectek_blackguard_SoundManager_dieSound 16L
#undef com_dialectek_blackguard_SoundManager_winnerSound
#define com_dialectek_blackguard_SoundManager_winnerSound 17L
/*
 * Class:     com_dialectek_blackguard_SoundManager
 * Method:    mute
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dialectek_blackguard_SoundManager_mute
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
