/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_BlackguardRenderer_View */

#ifndef _Included_com_dialectek_blackguard_BlackguardRenderer_View
#define _Included_com_dialectek_blackguard_BlackguardRenderer_View
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
