/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_Scene_DIRECTION */

#ifndef _Included_com_dialectek_blackguard_Scene_DIRECTION
#define _Included_com_dialectek_blackguard_Scene_DIRECTION
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
