/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_Scene_Floor */

#ifndef _Included_com_dialectek_blackguard_Scene_Floor
#define _Included_com_dialectek_blackguard_Scene_Floor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dialectek_blackguard_Scene_Floor_VERTS
#define com_dialectek_blackguard_Scene_Floor_VERTS 6L
#ifdef __cplusplus
}
#endif
#endif
