/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_Scene_Wall */

#ifndef _Included_com_dialectek_blackguard_Scene_Wall
#define _Included_com_dialectek_blackguard_Scene_Wall
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dialectek_blackguard_Scene_Wall_VERTS
#define com_dialectek_blackguard_Scene_Wall_VERTS 24L
#ifdef __cplusplus
}
#endif
#endif
