/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_Scene_Billboard */

#ifndef _Included_com_dialectek_blackguard_Scene_Billboard
#define _Included_com_dialectek_blackguard_Scene_Billboard
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dialectek_blackguard_Scene_Billboard_VERTS
#define com_dialectek_blackguard_Scene_Billboard_VERTS 6L
#ifdef __cplusplus
}
#endif
#endif
