/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dialectek_blackguard_BlackguardRenderer */

#ifndef _Included_com_dialectek_blackguard_BlackguardRenderer
#define _Included_com_dialectek_blackguard_BlackguardRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dialectek_blackguard_BlackguardRenderer_COLS
#define com_dialectek_blackguard_BlackguardRenderer_COLS 80L
#undef com_dialectek_blackguard_BlackguardRenderer_LINES
#define com_dialectek_blackguard_BlackguardRenderer_LINES 25L
#undef com_dialectek_blackguard_BlackguardRenderer_KEYBOARD_HIDDEN
#define com_dialectek_blackguard_BlackguardRenderer_KEYBOARD_HIDDEN -1L
#undef com_dialectek_blackguard_BlackguardRenderer_KEYBOARD_LOWER_CASE
#define com_dialectek_blackguard_BlackguardRenderer_KEYBOARD_LOWER_CASE 0L
#undef com_dialectek_blackguard_BlackguardRenderer_KEYBOARD_UPPER_CASE
#define com_dialectek_blackguard_BlackguardRenderer_KEYBOARD_UPPER_CASE 1L
/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    lockDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_lockDisplay
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    unlockDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_unlockDisplay
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    currentWindow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_currentWindow
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    getLines
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_getLines
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    getCols
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_getCols
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    getWindowChar
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_getWindowChar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    getScreenChar
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_getScreenChar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    showtext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_showtext
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    playerDir
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_playerDir
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    isBlind
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_isBlind
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    getSound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_getSound
  (JNIEnv *, jobject);

/*
 * Class:     com_dialectek_blackguard_BlackguardRenderer
 * Method:    displaymsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dialectek_blackguard_BlackguardRenderer_displaymsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
