# -*- coding: utf-8 -*-
# Deployment settings for Blackguard.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/8.0/s3e/makefile_builder/mkb.py', 'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/Blackguard.mkb', '--buildenv=VC12', '--debug', '--x86', '--no-ide', '--execute', '--deploy-only']
mkb = 'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/Blackguard.mkb'
mkf = ['c:\\marmalade\\8.0\\s3e\\s3e-default.mkf', 'c:\\marmalade\\8.0\\extensions\\s3eamazonads\\s3eamazonads.mkf', 'c:\\marmalade\\8.0\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\8.0\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\8.0\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\8.0\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\8.0\\platform_libs\\android\\amazon-ads-android-sdk\\amazon-ads-android-sdk.mkf', 'c:\\marmalade\\8.0\\platform_libs\\iphone\\amazon-ads-ios-sdk\\amazon-ads-ios-sdk.mkf', 'c:\\marmalade\\8.0\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\8.0\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\users\\tompo_000\\documents\\games\\roguelike\\blackguard\\ios\\appcore\\appcore.mkf', 'c:\\marmalade\\8.0\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\8.0\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\8.0\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\8.0\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\8.0\\extensions\\pvrtextool\\pvrtextool.mkf', 'c:\\users\\tompo_000\\documents\\games\\roguelike\\blackguard\\ios\\blackguard\\blackguard_deployment.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard\data', '.', 0),
]

assets['default'] = [
    ('c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/data/Anonymous.ttf', 'Anonymous.ttf', 0),
    ('c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/data/splashscreen.jpg', 'splashscreen.jpg', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Blackguard'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Blackguard'
    long_caption = 'Blackguard'
    version = [0, 0, 1]
    config = ['c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/data/app.icf']
    data_dir = 'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/data'
    mkb_dir = 'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard'
    iphone_link_lib = ['s3eAmazonAds']
    osx_ext_dll = ['c:/marmalade/8.0/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib']
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    provider = 'Dialectek'
    ws8_ext_native_only_dll = []
    win10_ext_uap_capabilities = []
    win10_ext_native_dll = []
    ws81_ext_native_only_dll = []
    android_external_res = []
    splashscreen_use_all = 1
    iphone_icon_dir = 'icons'
    win32_ext_dll = ['c:/marmalade/8.0/extensions/pvrtextool/lib/win32/PVRTexTool.dll']
    win10_ext_sdk_ref = []
    wp8_ext_capabilities = []
    ws8_extra_res = []
    ws81_ext_managed_dll = []
    win32_icon = 'c:/users/tompo_000/documents/games/roguelike/blackguard/ios/blackguard/icons/icon.png'
    iphone_link_libdir = ['c:/marmalade/8.0/extensions/s3eamazonads/lib/iphone']
    android_extra_application_manifest = ['c:/marmalade/8.0/extensions/s3eamazonads/source/android/ExtraAppManifests.xml']
    win10_extra_res = []
    ws8_ext_native_dll = []
    android_external_assets = []
    splashscreen = 'c:/users/tompo_000/documents/games/roguelike/blackguard/ios/blackguard/data/splashscreen.jpg'
    blackberry_extra_descriptor = []
    android_ext_target_sdk_version = [17]
    symbian7_uid = '0x10700001'
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    symbian8_uid = '0x10800001'
    wp81_ext_device_capabilities = []
    icon = 'c:/users/tompo_000/documents/games/roguelike/blackguard/ios/blackguard/icons/icon.png'
    win10_ext_capabilities = []
    linux_ext_lib = []
    android_ext_min_sdk_version = [4]
    wp81_ext_native_only_dll = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    brew_clsid = '0x10900001'
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = ['c:/marmalade/8.0/platform_libs/android/amazon-ads-android-sdk/third_party/lib/amazon-ads-5.5.149.jar', 'c:/marmalade/8.0/extensions/s3eamazonads/lib/android/s3eAmazonAds.jar']
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    wp81_ext_capabilities = []
    win10_ext_managed_dll = []
    iphone_extra_plist = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    android_supports_gl_texture = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    iphone_splash = 'c:/users/tompo_000/documents/games/roguelike/blackguard/ios/blackguard/data/splashscreen.jpg'
    wp8_ext_native_dll = []
    win10_ext_sdk_manifest_part = []
    win10_extra_pri = []
    win10_ext_device_capabilities = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    win32_aux_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = ['-Fc:/marmalade/8.0/platform_libs/iphone/amazon-ads-ios-sdk/third_party/Ads -framework AmazonAd', '-weak_framework AdSupport -weak_framework CoreLocation -weak_framework SystemConfiguration', '-weak_framework CoreTelephony -weak_framework MediaPlayer', '-weak_framework EventKit -weak_framework EventKitUI']
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_extra_packages = []
    android_so = ['c:/marmalade/8.0/extensions/s3eamazonads/lib/android/libs3eAmazonAds.so']
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    android_extra_strings = []
    target = {
         'mips' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_mips/Blackguard.so',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_mips/Blackguard.so',
                 },
         'gcc_x86' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_x86/Blackguard.so',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_x86/Blackguard.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_x86_tizen/Blackguard.s86',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_x86_tizen/Blackguard.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_mips/Blackguard.so',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_mips/Blackguard.so',
                 },
         'firefoxos' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_firefoxos/Blackguard.js',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_firefoxos/Blackguard.js',
                 },
         'gcc_arm_android' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_arm_android/Blackguard.so',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_arm_android/Blackguard.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_arm/Blackguard.s3e',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_arm/Blackguard.s3e',
                 },
         'naclx86_64' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_naclx86_64/Blackguard.so.s64',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_naclx86_64/Blackguard.so.s64',
                 },
         'aarch64_gcc' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_aarch64/Blackguard.s3e',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_aarch64/Blackguard.s3e',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_gcc_x86_android/Blackguard.so',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_gcc_x86_android/Blackguard.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_arm/Blackguard.s3e',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_arm/Blackguard.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Debug_Blackguard_VC12_x86/Blackguard.s86',
                   'release' : r'c:/Users/tompo_000/Documents/games/roguelike/Blackguard/ios/Blackguard/build_blackguard_vc12/Release_Blackguard_VC12_x86/Blackguard.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['default']

default = DefaultConfig()
